#export API_URL='http://localhost:8009'
#export UPLOAD_URL='http://localhost:9122'
export API_URL='https://staging-api.tidepool.io'
export UPLOAD_URL='https://staging-uploads.tidepool.io'
export UPLOAD_FILE_PATH='/Users/jhbate/Documents/Tidepool/src/data/2015.03.18_MM.ibf'